const effects = {
	"abecean": ["weak_frost", "fort_sneak", "weak_poison", "fort_rest"],
	"a_moth": ["dam_sta", "fort_conj", "dam_reg_mag", "fort_ench"],
	"ash_creep": ["dam_sta", "invisibility", "res_fire", "fort_dest"],
	"ash_hopp": ["rest_health", "fort_light", "res_shock", "weak_frost"],
	"ash_grass": ["res_fire", "weak_shock", "fort_lock", "fort_sneak"],
	"bear": ["rest_sta", "fort_health", "fort_one_h", "dam_reg_mag"],
	"bee": ["rest_sta", "rav_sta", "reg_sta", "weak_shock"],
	"beehive": ["res_poison", "fort_light", "fort_sneak", "fort_dest"],
	"berit": ["dam_sta", "res_fire", "fort_conj", "rav_sta"],
	"bleeding": ["weak_fire", "fort_block", "weak_poison", "res_magic"],
	"blister": ["dam_sta", "frenzy", "restore_health", "fort_smith"],
	"blue_butter": ["dam_sta", "fort_conj", "dam_reg_mag", "fort_ench"],
	"blue_dart": ["res_shock", "fort_pick", "rest_health", "fear"],
	"blue_flower": ["rest_health", "fort_conj", "fort_health", "dam_reg_mag"],
	"boar": ["fort_sta", "fort_health", "fort_block", "frenzy"],
	"bone": ["dam_sta", "res_fire", "fort_conj", "rav_sta"],
	"briar": ["rest_mag", "fort_block", "paralysis", "fort_mag"],
	"burnt_sprig": ["weak_fire", "fort_alt", "dam_reg_mag", "slow"],
	"butter": ["rest_health", "fort_barter", "dam_ling_sta", "dam_mag"],
	"canis": ["dam_sta", "fort_one_h", "fort_mark", "paralysis"],
	"c_skeever": ["rest_sta", "cure_disease", "res_poison", "rest_health"],
	"chaurus_egg": ["weak_poison", "fort_sta", "dam_mag", "invisibility"],
	"chaurus_ant": ["dam_sta", "fort_conj", "dam_reg_mag", "fort_ench"],
	"chick_egg": ["res_magic", "dam_reg_mag", "waterbreath", "dam_ling_sta"],
	"creep_c": ["rest_mag", "dam_reg_sta", "fort_carry", "weak_magic"],
	"crimson": ["dam_health", "dam_sta", "invisibility", "res_magic"],
	"cyrodilic": ["dam_sta", "fort_rest", "fear", "rav_health"],
	"daedra": ["rest_health", "dam_reg_sta", "dam_mag", "fear"],
	"deathbell": ["dam_health", "rav_sta", "slow", "weak_poison"],
	"dragon": ["res_fire", "fort_barter", "fort_ill", "fort_two_h"],
	"dwarven": ["weak_magic", "fort_ill", "reg_mag", "rest_mag"],
	"ecto": ["rest_mag", "fort_dest", "fort_mag", "dam_health"],
	"elves": ["rest_mag", "fort_mark", "weak_frost", "res_fire"],
	"parasol": ["dam_health", "fort_mag", "reg_health", "fort_two_h"],
	"eye_s_c": ["rest_sta", "rav_health", "dam_mag", "rest_health"],
	"falmer": ["dam_health", "frenzy", "res_poison", "fort_lock"],
	"felsaad": ["rest_health", "fort_light", "cure_disease", "res_magic"],
	"fire_salt": ["weak_frost", "res_fire", "rest_mag", "reg_mag"],
	"amanita": ["res_fire", "fort_two_h", "frenzy", "reg_sta"],
	"mirriam": ["res_frost", "fort_sneak", "rav_mag", "dam_reg_sta"],
	"frost_salt": ["weak_fire", "res_frost", "rest_mag", "fort_conj"],
	"garlic": ["res_poison", "fort_sta", "reg_mag", "reg_health"],
	"lichen": ["weak_shock", "rav_health", "weak_poison", "rest_mag"],
	"giant_toe": ["dam_sta", "fort_health", "fort_carry", "dam_reg_sta"],
	"gleamblossom": ["res_magic", "fear", "reg_health", "paralysis"],
	"glow_dust": ["dam_mag", "dam_reg_mag", "fort_dest", "res_shock"],
	"glow_mushroom": ["res_shock", "fort_dest", "fort_smith", "fort_health"],
	"grass_pod": ["res_poison", "rav_mag", "fort_alt", "rest_mag"],
	"hag_claw": ["res_magic", "dam_ling_mag", "fort_ench", "fort_barter"],
	"hag_feather": ["dam_mag", "fort_conj", "frenzy", "weak_shock"],
	"hang_moss": ["dam_mag", "fort_health", "dam_reg_mag", "fort_one_h"],
	"hawk_beak": ["rest_sta", "res_frost", "fort_carry", "res_shock"],
	"hawk_feather": ["cure_disease", "fort_light", "fort_one_h", "fort_sneak"],
	"hawk_egg": ["res_magic", "dam_reg_mag", "waterbreath", "dam_ling_sta"],
	"histcarp": ["rest_sta", "fort_mag", "dam_reg_sta", "waterbreath"],
	"honey": ["rest_sta", "fort_block", "fort_light", "rav_sta"],
	"human_f": ["dam_health", "paralysis", "rest_mag", "fort_sneak"],
	"human_h": ["dam_health", "dam_mag", "dam_reg_mag", "frenzy"],
	"ice_wraith": ["weak_frost", "fort_heavy", "invisibility", "weak_fire"],
	"imp_stool": ["dam_health", "dam_ling_health", "paralysis", "rest_health"],
	"jarrin_root": ["dam_health", "dam_mag", "dam_sta", "dam_reg_mag"],
	"jazbay": ["weak_magic", "fort_mag", "reg_mag", "rav_health"],
	"juniper": ["weak_fire", "fort_mark", "reg_health", "dam_reg_sta"],
	"l_antler": ["rest_sta", "fort_sta", "slow", "dam_reg_sta"],
	"lavender": ["res_magic", "fort_sta", "rav_mag", "fort_conj"],
	"l_moth": ["dam_mag", "fort_light", "reg_health", "invisibility"],
	"moon_sugar": ["weak_fire", "res_frost", "rest_mag", "reg_mag"],
	"tapinella": ["rest_mag", "dam_ling_health", "reg_sta", "fort_ill"],
	"mudcrab": ["rest_sta", "cure_disease", "res_poison", "res_fire"],
	"namira": ["dam_mag", "fort_lock", "fear", "reg_health"],
	"netch": ["paralysis", "fort_carry", "rest_sta", "fear"],
	"nightshade": ["dam_health", "dam_reg_mag", "dam_ling_sta", "fort_dest"],
	"nirnroot": ["dam_health", "dam_sta", "invisibility", "res_magic"],
	"barnacle": ["dam_mag", "waterbreath", "reg_health", "fort_pick"],
	"orange_dart": ["rest_sta", "rav_mag", "fort_pick", "dam_ling_health"],
	"pearl": ["rest_sta", "fort_block", "rest_mag", "res_shock"],
	"p_t_egg": ["rest_sta", "fort_lock", "weak_poison", "res_shock"],
	"p_bloom": ["dam_health", "slow", "fort_carry", "fear"],
	"mammoth": ["rest_sta", "fort_sneak", "weak_fire", "fear"],
	"purp_flower": ["rest_sta", "fort_sneak", "dam_ling_mag", "res_frost"],
	"red_flower": ["rest_mag", "rav_mag", "fort_mag", "dam_health"],
	"r_betty": ["dam_health", "fort_alt", "slow", "fort_carry"],
	"r_w_egg": ["rest_health", "fort_one_h", "dam_sta", "weak_magic"],
	"s_c_tooth": ["rest_sta", "fort_heavy", "fort_smith", "weak_poison"],
	"salmon_r": ["rest_sta", "waterbreath", "fort_mag", "reg_mag"],
	"salt": ["weak_magic", "fort_rest", "slow", "reg_mag"],
	"pholiota": ["weak_magic", "fort_ill", "reg_sta", "fort_carry"],
	"scathecraw": ["rav_health", "rav_sta", "rav_mag", "dam_ling_health"],
	"silverside": ["rest_sta", "dam_reg_sta", "rav_health", "res_frost"],
	"skeever_t": ["dam_reg_sta", "rav_health", "dam_health", "fort_light"],
	"slaught_egg": ["res_poison", "fort_pick", "dam_ling_health", "fort_sta"],
	"slaught_scale": ["res_frost", "dam_ling_health", "fort_heavy", "fort_block"],
	"s_antler": ["weak_poison", "fort_rest", "dam_ling_sta", "dam_health"],
	"s_pearl": ["rest_sta", "fort_one_h", "fort_rest", "res_frost"],
	"snowberry": ["res_fire", "fort_ench", "res_frost", "res_shock"],
	"spawn_ash": ["rav_sta", "res_fire", "fort_ench", "rav_mag"],
	"spider": ["dam_sta", "dam_reg_mag", "fort_lock", "fort_mark"],
	"sprig_sap": ["dam_reg_mag", "fort_ench", "fort_smith", "fort_alt"],
	"swamp_f_pod": ["res_shock", "dam_ling_mag", "paralysis", "rest_health"],
	"taproot": ["weak_magic", "fort_ill", "reg_mag", "rest_mag"],
	"thistle": ["res_frost", "rav_sta", "res_poison", "fort_heavy"],
	"torchbug": ["rest_sta", "dam_ling_mag", "weak_magic", "fort_sta"],
	"trama": ["weak_shock", "fort_carry", "dam_mag", "slow"],
	"troll": ["res_poison", "fort_two_h", "frenzy", "dam_health"],
	"t_cotton": ["res_magic", "fort_mag", "fort_block", "fort_barter"],
	"v_dust": ["invisibility", "rest_mag", "reg_health", "cure_disease"],
	"void_salt": ["weak_shock", "res_magic", "dam_health", "fort_mag"],
	"wheat": ["rest_health", "fort_health", "dam_reg_sta", "dam_ling_mag"],
	"white_cap": ["weak_frost", "fort_heavy", "rest_mag", "rav_mag"],
	"wisp_wrap": ["rest_sta", "fort_dest", "fort_carry", "res_magic"],
	"yellow_flower": ["res_poison", "fort_rest", "fort_health", "dam_reg_sta"],
}

const ingredients_label = {
	"abecean": "Abecean Longfin",
	"a_moth": "Ancestor Moth Wing",
	"ash_creep": "Ash Creep Cluster",
	"ash_hopp": "Ash Hopper Jelly",
	"ash_grass": "Ashen Grass Pod",
	"bear": "Bear Claws",
	"bee": "Bee",
	"beehive": "Beehive Husk",
	"berit": "Berit's Ashes",
	"bleeding": "Bleeding Crown",
	"blister": "Blisterwort",
	"blue_butter": "Blue Butterfly Wing",
	"blue_dart": "Blue Dartwing",
	"blue_flower": "Blue Mountain Flower",
	"boar": "Boark Tusk",
	"bone": "Bone Meal",
	"briar": "Briar Heart",
	"burnt_sprig": "Burnt Spriggan Wood",
	"butter": "Butterfly Wing",
	"canis": "Canis Root",
	"c_skeever": "Charred Skeever Hide",
	"chaurus_egg": "Chaurus Eggs",
	"chaurus_ant": "Chaurus Hunter Antennae",
	"chick_egg": "Chicken's Egg",
	"creep_c": "Creep Cluster",
	"crimson": "Crimson Nirnroot",
	"cyrodilic": "Cyrodilic Spadetail",
	"daedra": "Daedra Heart",
	"deathbell": "Deathbell",
	"dragon": "Dragon's Tongue",
	"dwarven": "Dwarven Oil",
	"ecto": "Ectoplasm",
	"elves": "Elves Ear",
	"parasol": "Emperor Parasol Moss",
	"eye_s_c": "Eye of Sabre Cat",
	"falmer": "Falmer Ear",
	"felsaad": "Felsaad Tern Feathers",
	"fire_salt": "Fire Salts",
	"amanita": "Fly Amanity",
	"mirriam": "Frost Mirriam",
	"frost_salt": "Frost Salts",
	"garlic": "Garlic",
	"lichen": "Giant Lichen",
	"giant_toe": "Giant's Toe",
	"gleamblossom": "Gleamblossom",
	"glow_dust": "Glow Dust",
	"glow_mushroom": "Glowing Mushroom",
	"grass_pod": "Grass Pod",
	"hag_claw": "Hagraven Claw",
	"hag_feather": "Hagraven Feathers",
	"hang_moss": "Hanging Moss",
	"hawk_beak": "Hawk Beak",
	"hawk_feather": "Hawk Feathers",
	"hawk_egg": "Hawk's Egg",
	"histcarp": "Histcarp",
	"honey": "Honeycomb",
	"human_f": "Human Flesh",
	"human_h": "Human Heart",
	"ice_wraith": "Ice Wraith Teeth",
	"imp_stool": "Imp Stool",
	"jarrin_root": "Jarrin Root",
	"jazbay": "Jazbay Grapes",
	"juniper": "Juniper Berries",
	"l_antler": "Large Antlers",
	"lavender": "Lavender",
	"l_moth": "Luna Moth Wing",
	"moon_sugar": "Moon Sugar",
	"tapinella": "Mora Tapinella",
	"mudcrab": "Mudcrab Chitin",
	"namira": "Namira's Rot",
	"netch": "Netch Jelly",
	"nightshade": "Nightshade",
	"nirnroot": "Nirnroot",
	"barnacle": "Nordic Barnacle",
	"orange_dart": "Orange Dartwing",
	"pearl": "Pearl",
	"p_t_egg": "Pine Thrush Egg",
	"p_bloom": "Poison Bloom",
	"mammoth": "Powdered Mammoth Tusk",
	"purp_flower": "Purple Mountain Flower",
	"red_flower": "Red Mountain Flower",
	"r_betty": "River Betty",
	"r_w_egg": "Rock Warbler Egg",
	"s_c_tooth": "Sabre Cat Tooth",
	"salmon_r": "Salmon Roe",
	"salt": "Salt Pile",
	"pholiota": "Scaly Pholiota",
	"scathecraw": "Scathecraw",
	"silverside": "Silverside Perch",
	"skeever_t": "Skeever Tail",
	"slaught_egg": "Slaughterfish Egg",
	"slaught_scale": "Slaughterfish Scale",
	"s_antler": "Small Antlers",
	"s_pearl": "Small Pearl",
	"snowberry": "Snowberries",
	"spawn_ash": "Spawn Ash",
	"spider": "Spider Egg",
	"sprig_sap": "Spriggan Sap",
	"swamp_f_pod": "Sawmp Fungal Pod",
	"taproot": "Taproot",
	"thistle": "Thistle Branch",
	"torchbug": "Torchbug Thorax",
	"trama": "Trama Root",
	"troll": "Troll Fat",
	"t_cotton": "Tundra Cotton",
	"v_dust": "Vampire Dust",
	"void_salt": "Void Salt",
	"wheat": "Wheat",
	"white_cap": "White Cap",
	"wisp_wrap": "Wisp Wrappings",
	"yellow_flower": "Yellow Mountain Flower",
}

const effects_label = {
	"cure_disease": "Cure Disease",
	"cure_poison": "Cure Poison",
	"dam_health": "Damage Health",
	"dam_mag": "Damage Magicka",
	"dam_reg_mag": "Damage Magicka Regen",
	"dam_sta": "Damage Stamina",
	"dam_reg_sta": "Damage Stamina Regen",
	"fear": "Fear",
	"fort_alt": "Fortify Alteration",
	"fort_barter": "Fortify Barter",
	"fort_block": "Fortify Block",
	"fort_carry": "Fortify Carry Weight",
	"fort_conj": "Fortify Conjuration",
	"fort_dest": "Fortify Destruction",
	"fort_ench": "Fortify Enchanting",
	"fort_health": "Fortify Health",
	"fort_heavy": "Fortify Heavy Armor",
	"fort_ill": "Fortify Illusion",
	"fort_light": "Fortify Light Armor",
	"fort_lock": "Fortify Lockpicking",
	"fort_mag": "Fortify Magicka",
	"fort_mark": "Fortify Marksman",
	"fort_one_h": "Fortify One-handed",
	"fort_pick": "Fortify Pickpocket",
	"fort_rest": "Fortify Restoration",
	"fort_smith": "Fortify Smithing",
	"fort_sneak": "Fortify Sneaking",
	"fort_sta": "Fortify Stamina",
	"fort_two_h": "Fortify Two-handed",
	"frenzy": "Frenzy",
	"invisibility": "Invisibility",
	"light": "Light",
	"dam_ling_health": "Lingering Damage Health",
	"dam_ling_mag": "Lingering Damage Magicka",
	"dam_ling_sta": "Lingering Damage Stamina",
	"night": "Night Eye",
	"paralysis": "Paralysis",
	"rav_health": "Ravage Health",
	"rav_mag": "Ravage Magicka",
	"rav_sta": "Ravage Stamina",
	"reg_health": "Regenerate Health",
	"reg_mag": "Regenerate Magicka",
	"reg_sta": "Regenerate Stamina",
	"res_fire": "Resist Fire",
	"res_frost": "Resist Frost",
	"res_magic": "Resist Magic",
	"res_poison": "Resist Poison",
	"res_shock": "Resist Shock",
	"rest_health": "Restore Health",
	"rest_mag": "Restore Magicka",
	"rest_sta": "Restore Stamina",
	"slow": "Slow",
	"spell_absorb": "Spell Absorbtion",
	"waterbreath": "Waterbreathing",
	"weak_fire": "Weakness to Fire",
	"weak_frost": "Weakness to Frost",
	"weak_magic": "Weakness to Magic",
	"weak_poison": "Weakness to Poison",
	"weak_shock": "Weakness to Shock",
}

// Fill effect selector
effect_inner = "";
for (var effect in effects_label) {
	effect_inner +=`<button class="effect" data-effect="${effect}">${effects_label[effect]}</button>`;
}
var effect_selector = document.getElementById("effect_selector");
effect_selector.innerHTML = effect_inner;

// Fill ingredients selector
ingredients_inner = "";
for (var ing in effects) {
	var paragraph = `<button class="ingredient" data-effect="${effects[ing].join(' ')}">${ingredients_label[ing]}</button>`;
	for (effect in effects[ing]) {
		paragraph +=`<button class="effect" data-effect="${effects[ing][effect]}">${effects_label[effects[ing][effect]]}</button>`
	}
	ingredients_inner += `<p>${paragraph}</p>`
}
var ingredient_selector = document.getElementById("ingredient_selector");
ingredient_selector.innerHTML = ingredients_inner;

function hover_event(ev) {
	var el = ev.target;
	var effects = el.dataset.effect.split(" ");
	document.querySelectorAll(".hovered").forEach(function(all_el) {
		all_el.classList.remove("hovered");
	});
	effects.forEach(function(effect) {
		document.querySelectorAll(`[data-effect*="${effect}"]`).forEach(function (node) {
			node.classList.add("hovered");
		});
	});
}

function click_event(ev) {
	var el = ev.target;
	var effects = el.dataset.effect.split(" ");
	document.querySelectorAll(".clicked").forEach(function(all_el) {
		all_el.classList.remove("clicked");
	});
	effects.forEach(function(effect) {
		document.querySelectorAll(`[data-effect*="${effect}"]`).forEach(function (node) {
			node.classList.add("clicked");
		});
	});
}

document.querySelectorAll("button").forEach(function(el) {
	el.addEventListener("mouseover", hover_event);
	el.addEventListener("click", click_event);
});

document.querySelectorAll("section").forEach(function(el) {
	el.addEventListener("mouseleave", function(ev) {
		document.querySelectorAll("button.hovered").forEach(function(all_el) {
			all_el.classList.remove("hovered");
		});
	});
});